---
title: "R t Rstudio"
author: "Vincent Guillemot & Amaury Vaysse"
date: "Lundi 15 novembre 2021"
output: 
  ioslides_presentation:
    css: styles.css
vignette: >
  %\VignetteIndexEntry{01packages}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

<style>
.forceBreak { -webkit-column-break-after: always; break-after: column; }
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE
)
```


## La différence entre R et Rstudio {.columns-2}


R est d'abord un **langage de programmation** qui a pour but principal de permettre d'analyser des données et de produire des représentations graphiques.

Mais c'est également un logiciel Open Source, libre et gratuit qui peut s'installer sur tous les systèmes d'exploitation classiques (Mac, Windows et Linux).

De plus la communauté des utilisateurs de R met à disposition 18261 (le 24/09/2021) packages qui permettent d'appliquer toutes les procédures statistiques imagineables, des plus classiques aux plus récentes.

<p class="forceBreak"></p>

Rstudio est à la fois le nom d'une entreprise à but non lucratif (*B Corps™*) qui met à disposition de la communauté, entre autres, des logiciels Open Source, libres et gratuits. Parmi ces logiciels : l'éditeur de programme éponyme Rstudio.

Rstudio est disponible également sur tous les systèmes d'exploitation classiques (Mac, Windows et Linux).

Rstudio permet de programmer en R dans un environnement fiable, riche et très complet. SOn interface graphique a été pensée pour permettre aux utilisateurs débutants de bénéficier de fonctionnalités permettant de les aider à maîtriser le langage, et beaucoup de fonctionnalités avancées pour les utilistauers aguerris!





