---
title: "Commandes et objets de base"
author: "Vincent Guillemot<br/>Amaury Vaysse"
date: "Lundi 15/11/2021"
output: 
  ioslides_presentation:
    css: styles.css
vignette: >
  %\VignetteIndexEntry{02dplyr}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

<style>
.forceBreak { -webkit-column-break-after: always; break-after: column; }
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE
)
```

## Bien se préparer à coder

  * Créer un projet dans ce dossier : 
     * Bien réfléchir au nom de ce projet
     * Bien réfléchir à l'endroit où ce projet sera situé
  * Créer un script
  * Savoir où sont les données, et sous quel format
  * Savoir ce que l'on veut faire !
  
# C'est parti pour les commandes de base !

## Le(s) prompt(s)

  * `>` : R attend une commande à exécuter
  * `+` : la commande qui a été entrée n'est pas complète car
    * il manque une parenthèse fermante
    * il manque un crochet fermant
    * il manque une accolade fermante
  * ` ` : la commande est en cours de traitement. On peut l'arrêter en cliquant sur le bouton "Stop"

## Une commande, c'est quoi ?

C'est une séquence d'opérations appliquées à des objets ou des valeurs qui sera donnée au compilateur de R pour interprétation.

  * "opération" : permet de transformer des entrées en sorties, p.ex. : la fonction `log`;
  * "objets" : structures de données, p.ex. : plus tard ;
  * "valeurs" : des briques de base, p.ex. : la valeur `0`. 

Une fois la commande écrite dans la console, on l'exécute en appuyant sur "Entrée".

## Exercice

Exécutez les commandes suivantes : 

  1. `1 + 1`
  2. `1+1`
  3. `log(10)`
  4. `log10(10)`

Remarquez l'utilisation des parenthèses pour appliquer une fonction !

## Opérations de base

On peut effectuer toutes les opérations de base en R : 

  * addition (`+`), soustraction (`-`), multiplication (`*`), division (`/`), exponentiation (`**` ou `^`)...
  
appliquer les fonctions mathématiques de base :

  * logarithme (`log`, `log2`, `log10`), exponentielle (`exp`) sinus (`sin`), cosinus (`cos`), tangente (`tan`)
  
On peut combiner les opérations et les fonctions, et gérer les priorités avec des parenthèses !

## Exercice

Imaginez une commande incluant le plus d'opérations et de fonctions de base et dont le résultat serait 2 !

## Un opérateur bien pratique, le `:`


